name: coospo_ios
description: App per la connessione e streaming di device COOSPO
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.11
  permission_handler: ^11.3.0
  socket_io_client: ^2.0.3+1
  geolocator: ^10.1.0
  apple_maps_flutter: ^1.2.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0 
  path: ^1.8.3     
  google_fonts: ^6.3.2
  lottie: ^3.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: true
  ios: true 
  image_path: "assets/icona coospo.png"