name: coospo_ios
description: A Bluetooth and GPS scanner app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^10.0.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
  flutter_blue_plus: ^1.32.11
  permission_handler: ^11.3.0
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true